apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::844050280722:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1MKNIQEW0747A
      username: system:node:{{EC2PrivateDNSName}}
    - rolearn: arn:aws:iam::844050280722:role/UdacityFlaskDeployCBKubectlRole
      username: build
      groups:
        - system:masters
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-19T05:49:30Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-01-19T05:49:30Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1837"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: cc55f400-d394-4a34-b4eb-6bae0fa29898
