apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::844050280722:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-G4AMMV3AVT7O
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::844050280722:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-20T11:23:35Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-01-20T11:23:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1383"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 79ebeefa-c71b-460d-8a97-3b33b36418de
