apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::844050280722:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-RLQ175X3QQZY
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::844050280722:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-01-19T17:40:15Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapRoles: {}
        f:mapUsers: {}
    manager: eksctl
    operation: Update
    time: "2021-01-19T17:40:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1771"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: b75bced1-ac70-4526-b8b4-8a97a3c0acc6
